# Site
repository: radonys/radonys.github.io
favicon: images/favicon.ico

# Personal info
name: Yash Srivastava
title: Data Science and Analytics | Software Development
email: yashsri@umd.edu
website: radonys.github.io

# Social links
linkedin_username: radonys
github_username:  radonys
twitter_username: yashsrivastav97
# facebook_username: yashsrivastava30
# instagram_username: yashsrivastava7
# dribbble_username: jekyll
# flickr_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

additional_links:
- title: Google Scholar link
  icon: fa-google
  url: https://scholar.google.com/citations?user=Pd4WGpUAAAAJ&hl=en
  
- title: Blogger link
  icon: fa-blogger
  url: http://radonys.blogspot.com/

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Yash and I'm a recent graduate student from University of Maryland. Thank you for visiting my website and hit me up to discuss about recent happenings in data science and new oppurtunities. 

  I am most skilled in: <mark>Python</mark>, <mark>SQL</mark> and <mark>Machine Learning</mark>. A list of my skills can be found below:

  <br>

  - Languages: Python, R, SQL (Postgres/MSSQL), Java, C/C++, HTML/CSS/JS
  - Data: ElasticSearch, Hadoop, Spark, Hive, Pig, Pandas, NumPy, Tableau, ETL
  - Frameworks: Keras, PyTorch, Scikit-Learn, OpenCV, Django, Matplotlib, Jupyter
  - Machine Learning: Classification, Regression, Clustering, Forecasting, Decision Trees, Neural Networks
  - Tools: Git, Linux, Amazon Web Services (AWS), Google Cloud (GCP), Databricks, MS Word/Excel/PowerPoint
  - Methodologies: Data Warehousing & Architecture, Scope & Requirement Gathering, Agile Development  


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data science and business intelligence some of my other interests and hobbies are:
   - Liverpool Football Club
   - Telling and listening stories
   - Table Tennis
   - Swimming
   - Indian and Chinese Food (especially sweets)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
