# Site
repository: radonys/radonys.github.io
favicon: images/favicon.ico

# Personal info
name: Yash Srivastava
title: Graduate Research Assistant @ UMD
email: yashsri@umd.edu
website: radonys.github.io

# Social links
linkedin_username: radonys
github_username:  radonys
twitter_username: yashsrivastav97
# facebook_username: yashsrivastava30
# instagram_username: yashsrivastava7
# dribbble_username: jekyll
# flickr_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

additional_links:
- title: Google Scholar link
  icon: fa-google
  url: https://scholar.google.com/citations?user=Pd4WGpUAAAAJ&hl=en

additional_links:
- title: Blogger link
  icon: fa-blogger
  url: http://radonys.blogspot.com/

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Yash and I'm a second-year graduate student at University of Maryland. I have worked and gained academic and professional experiences in <mark>data science</mark>, <mark>data engineering</mark> and <mark>business intelligence</mark> as part of my coursework, assitantships and internships. I am looking forward to start my full-time professional career in a data-driven role starting February 2021. 

  I am most skilled in: <mark>Python</mark>, <mark>SQL</mark> and <mark>Machine Learning</mark>. A list of my skills can be found below:


  - Programming Languages: R, Java, C++, HTML/CSS/JS
  - Data Engineering: NoSQL, Hadoop, Pig, Hive, Spark, Airflow, Kafka, ETL
  - Databases: MySQL, PostgreSQL, ElasticSearch, Cassandra, MS SQL
  - Machine Learning: Decision Trees, Neural Networks, Regression, Text Mining, Computer Vision
  - Business Analysis: Data Warehousing & Architecture, Scope & Requirement Gathering
  - Tools & Frameworks: Git, Linux, AWS, Pandas, NumPy, Matplotlib, Tableau, Power BI, Jenkins 


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data science and business intelligence some of my other interests and hobbies are:
   - Liverpool Football Club
   - Telling and listening stories
   - Table Tennis
   - Swimming
   - Indian and Chinese Food (especially sweets)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
