# Site
repository: radonys/radonys.github.io
favicon: images/favicon.

# Content configuration version
version: 2

# Personal info
name: Yash Srivastava
title: Data Science and Analytics | Software Development
email: yash.srivastava@outlook.com
website: radonys.github.io

# Social links
linkedin_username: radonys
github_username:  radonys
twitter_username: yashsrivastav97
# facebook_username: yashsrivastava30
# instagram_username: yashsrivastava7
# dribbble_username: jekyll
# flickr_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

additional_links:
- title: Google Scholar link
  icon: fab fa-google
  url: https://scholar.google.com/citations?user=Pd4WGpUAAAAJ&hl=en
  
- title: Blogger link
  icon: fab fa-blogger
  url: http://radonys.blogspot.com/

# About Section
# about_title: About Me
about_profile_image: images/data_science_data_analyst_software_development_data_engineer.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Yash and I'm a recent graduate student from University of Maryland. Thank you for visiting my website and hit me up to discuss about recent happenings in data science and new oppurtunities. 

  I am most skilled in: <mark>Python</mark>, <mark>SQL</mark> and <mark>Machine Learning</mark>. A list of my skills can be found below:

  <br>

  - **Programming Languages**: Python, R, SQL (Postgres/MSSQL), Java, C/C++, HTML/CSS/JS
  - **Data**: ElasticSearch, Hadoop, Spark, Hive, Pig, Pandas, NumPy, Tableau, ETL
  - **Frameworks**: Keras, PyTorch, Scikit-Learn, OpenCV, Django, Matplotlib, Jupyter
  - **Machine Learning**: Classification, Regression, Clustering, Forecasting, Decision Trees, Neural Networks
  - **Tools**: Git, Linux, Amazon Web Services (AWS), Google Cloud (GCP), Databricks, MS Word/Excel/PowerPoint
  - **Methodologies**: Data Warehousing & Architecture, Scope & Requirement Gathering, Agile Development

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: NWO.AI
        link: nwo.ai
        sub_title: Data Engineer
        dates: March 2021 - Present
        description: | # this will include new lines to allow paragraphs
          - Lead data engineering efforts and build social, financial and research datasets ingesting 1M+ data points daily from 10 sources, resulting in identifying and forecasting 20M+ trends and context spaces for Fortune 500 clients.
          - Systematized monitoring, automation, and validation of datasets increasing processing efficiency by 85%.
          - djd
          - **Technologies used: Python, GCP, BigQuery, SQL, PyData, Airflow, Selenium, Git, HTML/CSS/JS**

      - layout: left
        title: University of Maryland
        link: umd.edu
        sub_title: Research Assistant (Business Research)
        dates: September 2019 - December 2020
        description: | # this will include new lines to allow paragraphs
          - Collected and examined online interactions of 30-plus companies from 6 social media platforms showing 25% increase in customer satisfaction and positive feedback.
          - Investigated perception towards brand using sentiment and statistical analysis reflecting 7% positive response.
          - **Technologies used: Python (pandas/scikit-learn/numpy), Selenium, PyTorch, SQL, OpenCV, AWS**

      - layout: left
        title: CERTIFY Health
        link: certify.me
        sub_title: Business Intelligence Engineer
        dates: June 2020 - August 2020
        description: | # this will include new lines to allow paragraphs
          - Designed data synchronization API between Inventory Management and eCommerce platform fastening order fulfillment by 60%.
          - Integrated Fedex and UPS APIs in CRM system reducing label generation and shipment times by 3 days.
          - Systematized spreadsheet data management from 10+ sources using ER diagrams and database design increasing data retrieval efficiency by 80%.
          - Developed affiliate programs with WordPress and HubSpot for CERTIFY website recording monthly sales of $300,000+.
          - Executed two-week Google Analytics campaign in collaboration with India and China teams leading to 100,000+ website impressions.
          - **Technologies used: Python, Excel, SQL, Tableau, PHP, Azure, Wordpress, Confluence, Lucidchart**

      - layout: left
        title: Indian Institute of Information Technology, Sri City
        link: iiits.ac.in
        sub_title: Undergraduate Student Researcher
        dates: July 2017 - May 2019
        description: | # this will include new lines to allow paragraphs
          - Surveyed 25+ criterion functions used with Convolutional Neural Networks (CNN) for Face Recognition tasks leading to research publication at NCVPRIPG 2019 (http://bit.ly/2Mdi1NG).
          - Conceptualized two deep-learning based Face Recognition methods with Hard-Mining Loss and Parametric-Sigmoid layers each showing 97% plus verification accuracy.
          - Investigated 10+ dataset and architecture advancements in Visual-Question Answering domain using Deep Learning with a conference paper in CVIP 2020 (http://bit.ly/3amuFSs).
          - Published two face recognition methods papers at CVIP 2020 (http://bit.ly/2NHT5Or) and CICT 2019 (http://bit.ly/3oy4IEp) receiving best paper award for Hard-Mining Loss.
          - **Technologies used: Python (pandas/scikit-learn/numpy), PyTorch, Keras, MxNet, OpenCV, Tensorboard**

      - layout: left
        title: CERN (European Organization for Nuclear Research)
        link: home.cern
        sub_title: Software Engineer (Google Summer of Code)
        dates: May 2018 - August 2018
        description: | # this will include new lines to allow paragraphs
          - Spearheaded database migration from MySQL to Elasticsearch for DIRAC open-source project increasing process time efficiency of nuclear experiment data management and analysis by 70%.
          - Revamped database access functions to support Elasticsearch backend overseeing 50% boost in response time.
          - Programmed unit and integration tests producing 25+ tests for execution before production launch.
          - **Technologies used: Python, SQL, ElasticSearch, pytest, Django, Git, Travis CI, Jenkins**

      - layout: left
        title: Physiz
        link: physiz.com
        sub_title: Data Scientist
        dates: August 2017 - September 2017
        description: | # this will include new lines to allow paragraphs
          - Built the leaf-detection pipeline from live-farm image feed using CNNs and PlantCV with 70% detection accuracy.
          - Surveyed 30+ deep-learning mechanisms for geographical nutrient supply analysis summarizing 3 top solutions for research and development.
          - **Technologies used: Python (numpy/pandas/scikit-learn/matplotlib), Keras, CouchDB, OpenCV**

      - layout: left
        title: Bobble AI
        link: bobble.ai
        sub_title: Software QA Engineer
        dates: May 2017 - June 2017
        description: | # this will include new lines to allow paragraphs
          - Diagnosed 10 functional and performance bugs in the Bobble Keyboard application.
          - Programmed test scenarios for 15+ modules of the application covering 20 boundary cases.
          - Overhauled automation tests using Python-based Culebra tool fastening production testing time by 40%.
          - Summarized 5000+ Play Store application reviews with data analytics and visualization and identified 8 customer pain points and preferences.
          - **Technologies used: Java, Python, UI Automator, Espresso, Android Studio, GitHub**

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Maryland, College Park
        caption: August 2019 - December 2020
        sub_title: M.S. Information Systems (GPA 3.93)
        description: | # this will include new lines to allow paragraphs
          -djjdjd

      - layout: left
        title: Indian Institute of Information Technology, Sri City
        dates: 2015 - 2019
        sub_title: B.Tech. Computer Science (GPA 3.6)
        description: | # this will include new lines to allow paragraphs
          -dhjdhdhdh

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Programming Languages**: Python, R, SQL (Postgres/MSSQL), Java, C/C++, HTML/CSS/JS
      **Data**: ElasticSearch, Hadoop, Spark, Hive, Pig, Pandas, NumPy, Tableau, ETL
      **Frameworks**: Keras, PyTorch, Scikit-Learn, OpenCV, Django, Matplotlib, Jupyter
      **Machine Learning**: Classification, Regression, Clustering, Forecasting, Decision Trees, Neural Networks
      **Tools**: Git, Linux, Amazon Web Services (AWS), Google Cloud (GCP), Databricks, MS Word/Excel/PowerPoint
      **Methodologies**: Data Warehousing & Architecture, Scope & Requirement Gathering, Agile Development
      

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in data science and business intelligence some of my other interests and hobbies are:
#   - Liverpool Football Club
#   - Telling and listening stories
#   - Table Tennis
#   - Swimming
#   - Indian and Chinese Food (especially sweets)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
